import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
    auto: [
        {
            type: 'autogenerated',
            dirName: '.', // '.' means the current docs folder
        },
    ]
};

export default sidebars;
